"""empty message

Revision ID: 4e5b981f2852
Revises: 6cf49e63d71d
Create Date: 2018-05-05 12:14:05.360621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5b981f2852'
down_revision = '6cf49e63d71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('class_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'class_level')
    # ### end Alembic commands ###
