"""empty message

Revision ID: 6cf49e63d71d
Revises: 2ff36d2b11cf
Create Date: 2018-05-05 11:57:45.391196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf49e63d71d'
down_revision = '2ff36d2b11cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('req_class', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'req_class')
    # ### end Alembic commands ###
